"""
Pydantic schema.
"""

from pydantic import BaseModel


class CreateContact(BaseModel):
    """
    This model is used to create the contact,
    hence the missing ID field.
    """
    lastname: str
    initials: str
    firstname: str
    street: str
    house_number: str
    postalcode: str
    residence: str


class Contact(CreateContact):
    """
    This adds the ID field, completing the model.
    ID field is autogenerated by the database.
    """
    contact_id: int

    class Config:
        orm_mode = True

